### ISSUE TITLE
[Paper 1.20.6] Unable to break blocks after death

### ISSUE THREAD

**Issue by chxseh** [Athlaeos/ValhallaMMO#11]
With the default configuration on a Paper 1.20.6 server, you can't break a block after you die until you relog, at least with `custom_mining_speeds` set to true. 

This might be caused by the new changes that Paper made:

* https://forums.papermc.io/threads/important-dev-psa-future-removal-of-cb-package-relocation.1106/
* https://forums.papermc.io/threads/paper-velocity-1-20-6.1152/

**Comment by Athlaeos** [comment]
It's unrelated to these paper changes, but yeah I'm not entirely sure why it's happening. After death the player is "fatigued" again which allows the custom mining system to function, but for some reason doing this fatiguing once doesn't work but twice it does. 
Fixed it though, I'll push the change right away

**Comment by Athlaeos** [comment]
Yeah, sorry, I know I said I would but some other stuff came up and I can't in good conscience release the plugin as it is now. It completely breaks on 1.21. I'll release it as soon as I'm able
