### ISSUE TITLE
sometimes our players get -2 or -3 skillpoints.

### ISSUE THREAD

**Issue by LxvtS** [Athlaeos/ValhallaMMO#12]
we don't know when or why, just happens randomly and doesnt get any better since they have to level up to get it back topositive again, making the gameplay a lot tougher than needed be...

**Comment by Athlaeos** [comment]
It's a known bug, likely caused by NG+ loops as the plugin incorrectly guesses how many skill points you ought to have

**Comment by Athlaeos** [comment]
The most recent update might have fixed it!

**Comment by Athlaeos** [comment]
Since the update I haven't had this issue reported since, so I'm gonna assume the solution fixed it!
