### ISSUE TITLE
Allow leaderboard placeholders to be used without the need for a player

### ISSUE THREAD

**Issue by DevPGSV** [Athlaeos/ValhallaMMO#15]
Currently, the following command:

`/papi parse --null %valhallammo_leaderboard_power_1%`
Resolves to:`%valhallammo_leaderboard_power_1%`
The variable resolves to itself.

Only when a username is provided, the variable resolves correctly:
`/papi parse DevPGSV %valhallammo_leaderboard_power_1%`
Resolves to: `&cLV0 &7PlayerName`

This breaks using the leaderboard placeholders in any leaderboard.

Currently, I'm trying to set those placeholder as (citizens) NPC names:
https://wiki.citizensnpcs.co/Frequently_Asked_Questions#My_PlaceholderAPI_Placeholder_Works_In_Chat.2C_But_Not_On_An_NPC

I'd like to request a change to the leaderboard placeholders (and any other that is not related to the player executing the command) to be available in a global context.

Thank you!

**Comment by Athlaeos** [comment]
will do!
