### ISSUE TITLE
Players gettting an unfair advantage with AFK fishfarms

### ISSUE THREAD

**Issue by reyes256** [Athlaeos/ValhallaMMO#20]
is it possible to prevent players from leveling up using afk fishfarms?

it feels wrong that a player can just afk and get 5x the amount of progress in just one night, and other players have to work for it for weeks.

**Comment by Athlaeos** [comment]
I've recently quadrupled the exp output of fishing, and to prevent AFK-fishing i can implement a similar system i applied on the combat skills where fishing in a single area too much will nuke your exp gains for it, does that sound good?
