### ISSUE TITLE
[IMPROVEMENTS] Crafter Improvements.

### ISSUE THREAD

**Issue by NagasonicDev** [Athlaeos/ValhallaMMO#31]
The crafter block can't craft items overridden by ValhallaMMO. It would be great if this could be fixed. I understand that it could make it unbalanced, but it would be cool if it was in config at least.

**Comment by Athlaeos** [comment]
This is actually intentional as crafter API sucks right now and is too difficult to work with to be worth the effort. I'll keep it as is until crafter API improves

**Comment by NagasonicDev** [comment]
Ok, thanks for the quick response.
